name: Check PR title
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: pinnacles/github-action-module-release/.github/actions/validate-pr-title@v4.2.1
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

