name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on:
      - codebuild-github-actions-runner-${{ github.run_id }}-${{ github.run_attempt }}
      - image:ubuntu-7.0
      - instance-size:medium
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - uses: pinnacles/github-action-module-release/.github/actions/release-by-merge@v4.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

